### ISSUE TITLE
High CPU usage of jawaw.exe on idle

### ISSUE THREAD

**Issue by joffs** [imTigger/webapp-hardware-bridge#27]
Happily using this great tool for some projects where I need to print, obviously. Just noticed a high cpu usage of jawaw.exe while idling in the background (10% to 50%, depending on CPU cores). Confirmed on at least 4 computers (all Windows 10). Versions checked: 0.10 - 01.13. Installed using whb-0.1x.0.exe. This happens with configured and unconfigured setups. Haven't tried with just the .jar files. Maybe you are aware of this.

**Comment by joffs** [comment]
Switching included JRE with Oracle JRE doesn't make a difference, same high CPU usage.

**Comment by navarro-j** [comment]
Open the configurator, right click and delete the weigh Serial COM3

**Comment by joffs** [comment]
Wow, very elegant solution, works perfectly! Thank you very much for pointing this out. 

Seeing the "Close with comment" button below, I was wondering where this issue would go afterwards and found another issue with the same problem and solution. I know better now to look into closed issues before posting a new one. ;)

Thanks again saving CPU time!
