### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by eeng** [imTigger/webapp-hardware-bridge#8]
Hi. First of all, thank you very much for this application, I think it's exactly what we were looking for.

I've just built master from source (v0.10.1) and I noticed the server is consuming 100% of the CPU all the time, as soon as it starts. I tried on my Mac and on CentOS. Is it normal? Have you noticed the same behaviour?

Keep up the good work!

**Comment by eeng** [comment]
Mmm weird... After some changes in the `settings.json` I'm not experiencing this anymore.
Closing the issue for now.

**Comment by flilloa** [comment]
> Mmm weird... After some changes in the `settings.json` I'm not experiencing this anymore.
> Closing the issue for now.

Can you tell me what changes do you make to the settings.json to reduce 100% CPU?,  I'm facing the same issue

**Comment by eeng** [comment]
If I remember correctly, I think the problem was the `"serials"` field which by default contained an example port not present on my machine. Try removing it an let me know if it helps.

**Comment by marcoleuti** [comment]
> If I remember correctly, I think the problem was the `"serials"` field which by default contained an example port not present on my machine. Try removing it an let me know if it helps.

I can confirm, deleting all the unused ports, saving and restarting the application the cpu usage dropped to 0%
